### ISSUE TITLE
nereon.com does not get built in CI

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/nereon.github.io#2]
The site builds locally after https://github.com/riboseinc/nereon.com/commit/63a1a9f18a36ec0fdb5af1decb8ef2301633e2ec but nereon.com remains unreachable.

**Comment by ronaldtse** [comment]
We don't have that setup yet, thanks for letting me know. Ping @kwkwan , thanks!

**Comment by ronaldtse** [comment]
It's done now!
